# Using Python for Research Homework: Week 2

In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe (noughts and crosses) simulator and evaluate basic winning strategies.

### Exercise 1

Tic-tac-toe (or noughts and crosses) is a simple strategy game in which two players take turns placing a mark on a 3x3 board, attempting to make a row, column, or diagonal of three with their mark. In this homework, we will use the tools we've covered in the past two weeks to create a tic-tac-toe simulator and evaluate basic winning strategies.

In the following exercises, we will learn to create a tic-tac-toe board, place markers on the board, evaluate if either player has won, and use this to simulate two basic strategies.

#### Instructions 

- For our tic-tac-toe board, we will use a numpy array with dimension 3 by 3. 
- Make a function `create_board()` that creates such a board with the value of each cell set to the integer `0`.
- Call `create_board()` and store it.

In [2]:
import numpy as np

def create_board():
    return np.zeros((3,3))


### Exercise 2

Players 1 and 2 will take turns changing values of this array from a 0 to a 1 or 2, indicating the number of the player who places a marker there.

#### Instructions 

- Create a function `place(board, player, position)`, where:
    - `player` is the current player (an integer 1 or 2).
    - `position` is a tuple of length 2 specifying a desired location to place their marker.
    - Your function should only allow the current player to place a marker on the board (change the board position to their number) if that position is empty (zero).
- Use `create_board()` to store a board as `board`, and use `place` to have Player 1 place a marker on location `(0, 0)`.

In [3]:
def place(board, player, position):
    r_index, c_index = position

    if board[r_index][c_index] == 0:
        board[r_index][c_index] = player

board = create_board()
place(board, 1, (0,0))


### Exercise 3

In this exercise, we will determine which positions are available to either player for placing their marker.

#### Instructions 
- Create a function `possibilities(board)` that returns a list of all positions (tuples) on the board that are not occupied (0). (Hint: `numpy.where` is a handy function that returns a list of indices that meet a condition.)
- `board` is already defined from previous exercises. Call `possibilities(board)` to see what it returns!

In [4]:
def possibilities(board):
    results = []
    indices = np.where(board == 0)

    for index, r_index in enumerate(indices[0]):
        c_index = indices[1][index]
        
        position = (r_index, c_index)

        results.append(position)

    return results

possibilities(board)



[(0, 1), (0, 2), (1, 0), (1, 1), (1, 2), (2, 0), (2, 1), (2, 2)]

### Exercise 4

The next step is for the current player to place a marker among the available positions. In this exercise, we will select an available board position at random and place a marker there.

#### Instructions 

- Write a function `random_place(board, player)` that places a marker for the current player at random among all the available positions (those currently set to 0).
    - Find possible placements with `possibilities(board)`.
    - Select one possible placement at random using `random.choice(selection)`.
- `board` is already defined from previous exercises. Call `random_place(board, player)` to place a random marker for Player 2, and store this as board to update its value.

In [5]:
import random 
random.seed(1)

def random_place(board, player):
    position = random.choice(possibilities(board))
    place(board, player, position)

random_place(board,2)
print(board)


[[1. 0. 0.]
 [2. 0. 0.]
 [0. 0. 0.]]


### Exercise 5

We will now have both players place three markers each.

#### Instructions 

- A new `board` is already given. Call `random_place(board, player)` to place three pieces each on board for players 1 and 2.
- Print board to see your result.

In [6]:
random.seed(1)
board = create_board()
piece_count = 0

while piece_count < 6:
    if piece_count % 2 == 0:
        random_place(board, 1)
        piece_count += 1
    else:
        random_place(board, 2)
        piece_count += 1

print(board)


[[2. 2. 1.]
 [0. 1. 0.]
 [0. 1. 2.]]


### Exercise 6

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Make a function `row_win(board, player)` that takes the player (integer) and determines if any row consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `row_win` to check if Player 1 has a complete row.

In [7]:
def row_win(board, player):
    for row in board:
        for value in row:
            if player != value:
                return False

        return True

row_win(board, 1)

False

### Exercise 7

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Make a function `col_win(board, player)` that takes the player (integer) and determines if any column consists of only their marker. 
    - Have it return `True` if this condition is met and `False` otherwise.
- `board` is already defined from previous exercises. Call `col_win` to check if Player 1 has a complete row.

In [8]:
def col_win(board, player):
    t_board = np.transpose(board)

    return row_win(t_board, player)

col_win(board, 1)

False

### Exercise 8

In the next few exercises, we will make functions that verify if either player has won the game.

#### Instructions 
- Finally, create a function `diag_win(board, player)` that tests if either diagonal of the board consists of only their marker. Have it return `True` if this condition is met, and `False` otherwise.
- `board` has been slightly modified from a previous exercise. Call `diag_win` to check if Player 2 has a complete diagonal.

In [9]:
board[1,1] = 2

def diag_win(board, player):
    diag = [[(0,0), (1,1), (2,2)], [(0,2), (1,1), (2,0)]]
    
    for profile in diag:
        count = 0
        
        for position in profile:
            x, y = position
            if player == board[x][y]:
                count += 1

        if count == 3:
            return True

    return False

diag_win(board, 2)
            

True

### Exercise 9

In the next few exercises, we will make functions that check whether either player has won the game.

#### Instructions 
- Create a function `evaluate(board)` that uses `row_win`, `col_win`, and `diag_win` functions for both players. If one of them has won, return that player's number. If the board is full but no one has won, return -1. Otherwise, return 0.
- `board` is already defined from previous exercises. Call evaluate to see if either player has won the game yet.

In [10]:
def evaluate(board):
    winner = 0
    for player in [1, 2]:
        if row_win(board, player) or col_win(board, player) or diag_win(board, player):
            return player
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

evaluate(board)

2

### Exercise 10

In this exercise, we will use all the functions we have made to simulate an entire game.

#### Instructions 

- `create_board()`, `random_place(board, player)`, and `evaluate(board)` have been created in previous exercises. Create a function `play_game()` that:
    - Creates a board.
    - Alternates taking turns between two players (beginning with Player 1), placing a marker during each turn.
    - Evaluates the board for a winner after each placement.
    - Continues the game until one player wins (returning 1 or 2 to reflect the winning player), or the game is a draw (returning -1).
- Call play_game 1000 times, and store the results of the game in a list called `results`.

In [11]:
random.seed(1)

'''
def play_game():
    board = create_board()
    moves_made = 0
    
    while evaluate(board) == 0:
        if moves_made % 2 == 0:
            random_place(board, 1)
            moves_made += 1
        else:
            random_place(board, 2)
            moves_made += 1

    return evaluate(board)

results = [play_game() for i in range(1000)]

results.count(1)
'''

411

#### Exercise 11

In the previous exercise, we see that when guessing at random, it's better to go first, as expected. Let's see if Player 1 can improve their strategy. 

#### Instructions 
- Create a function `play_strategic_game()`, where Player 1 always starts with the middle square, and otherwise both players place their markers randomly.
- Call `play_strategic_game` 1000 times.

In [12]:
random.seed(1)

def continue_game(board):
    # figure out player
    non_zero = np.where(board != 0)

    moves_made = len(non_zero[0])
    
    while evaluate(board) == 0:
        if moves_made % 2 == 0:
            random_place(board, 1)
            moves_made += 1
        else:
            random_place(board, 2)
            moves_made += 1

    return evaluate(board)
    
def play_strategic_game():
    board = create_board()
    board[1][1] = 1

    return continue_game(board)

result = []

for i in range(1000):
    result.append(play_strategic_game())

print(result)
result.count(1)

[2, -1, 1, 1, -1, 2, -1, -1, 1, -1, 2, -1, -1, 1, 1, -1, 2, -1, -1, 1, -1, 1, -1, 2, 1, -1, -1, 1, -1, 1, 2, 1, -1, 1, -1, 2, -1, 1, 1, 2, 1, 1, 1, 1, -1, 2, 1, -1, -1, 1, 2, 1, 1, -1, 1, 2, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, -1, -1, -1, 1, 1, 1, 2, -1, 1, 1, 1, 1, 2, 1, -1, 2, 1, 1, 1, 2, -1, 1, 2, -1, 2, 1, -1, 2, -1, 1, 2, -1, -1, 1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, 1, 1, -1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, -1, 1, -1, -1, 1, -1, 1, 2, 2, 1, -1, -1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, -1, 1, 1, 1, -1, 1, -1, 1, 1, 1, 1, 2, -1, 1, 1, -1, -1, 1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1, 1, -1, 2, -1, 1, 1, -1, 1, -1, -1, 1, 2, -1, 2, -1, -1, 1, 1, 1, 1, 2, -1, 2, 1, 1, 1, -1, 2, 1, 2, -1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, -1, 1, 1, 1, -1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 2, -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, -1, -1, -1, -1, 2, -1, 1, 1, -1, 1, -1, -1, 1, 1, -1, 1, -1, 2, 1, -1, 1, 1, 1, -1, -1, 1, 2, 2, 2, 1, 2, 1, 1, -1, 1, -1, -1, -1, -1, -1, -1, -1, 1,

492

In [14]:
random.seed(1)

def play_game():
    board = create_board()
    current_player = 1
    
    while True:
        random_place(board, current_player)
        result = evaluate(board)
        
        if result != 0:  # Game has ended
            return result
        
        # Switch player
        current_player = 2 if current_player == 1 else 1

results = [play_game() for i in range(1000)]

results.count(1)

411